# Generated by Django 2.2.5 on 2019-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=50, verbose_name='Local')),
                ('region', models.CharField(max_length=20, verbose_name='Região')),
                ('latitude', models.CharField(max_length=20, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=20, verbose_name='Longitude')),
                ('time_zone', models.CharField(max_length=50, verbose_name='Timezone')),
                ('elevation', models.CharField(max_length=20, verbose_name='Elevação')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locais',
                'ordering': ('local_name', 'region'),
            },
        ),
    ]
