# Generated by Django 2.2.5 on 2019-10-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customlocation',
            options={'ordering': ('name', 'region'), 'verbose_name': 'local', 'verbose_name_plural': 'locais'},
        ),
        migrations.RenameField(
            model_name='customlocation',
            old_name='local_name',
            new_name='name',
        ),
    ]
