# Generated by Django 3.2.2 on 2021-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resh', '0002_auto_20191013_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
